FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# rutm

RUTM backend API

# Group Объекты

## Получить список объектов [/allobjects]

### Список объектов [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes(object)
        - items (array[RutmObject])

# Group Маршрут

## Маршруты [/route/{address}]

+ Parameters
    - address: `addr` (number) - Адрес объекта

### Получить маршрут объекта [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes(Route)

### Установить маршрут [POST]
+ Request (application/json; charset=utf-8)
    + Attributes(Route)
    
+ Response 201

# Group История

## Получить историю [/history/{address}]

+ Parameters
    - address: `addr` (number) - Адрес объекта

### Получить историю объекта [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes(History)

# Group Ограничения
    
## Получить ограничения [/restrictions]

### Получить список ограничений [GET]
+ Response 200 (application/json; charset=utf-8)
    + Attributes(object, fixed-type)
        - items (array[Restriction]) - Список ограничений

### Создать ограничение [POST]
+ Request (application/json; charset=utf-8)
    + Attributes(RestrictPolygon)
    
+ Response 201
    
    + Header
        
            Location: /restrictions/{id} - URL-escaped путь к созданному ограничению

## Удалить ограничение [/restrictions/{id}]

### Удалить ограничение [DELETE]
+ Response 204


# Data Structures

## RutmObjectType(enum[number])
Тип объекта
### Members
- `0` - Неизвестно

## RutmObjectSource(enum[string])
Источник, откуда получения информация об объекте
### Members
- `aznv` - АЗНВ
- `mavlink` - МAVLink

## Point(object, fixed-type)
Точка, входит в несколько сущностей
### Properties
- index: 0 (number) - Номер точки
- latitude: 55 (number) - Долгота
- longitude: 37 (number) - Широта

## Route(object, fixed-type)
Маршрут
### Properties
- points (array[Point]) - Точки маршрута

## History(Route)
История

## RutmObject(object, fixed-type)
Описание объекта
### Properties
- latitude: `55.66` (number) - Широта
- longitude: `37.56` (number) - Долгота
- course: `45` (number) - Курс
- type: `0` (RutmObjectType) - Тип
- address: `1124` (number) - Адрес
- callsign: `fff` (string) - Позывной
- source: `aznv` (RutmObjectSource) - Источник
- route (Route) - Маршрут
- history (History) - История ??
- conflict_status: `false` (boolean) - true - есть конфликт
- daa_status: `код ситуации + запрещенный сектор - начало и конец?` (string) - статус DAA

## RestrictPolygon(object, fixed-type)
Полигон ограничения
### Properties
- polygon (array[Point]) - Граница ограниичения

## Restriction(RestrictPolygon, fixed-type)
Ограничение
### Properties
- id: `0` (number) - Идентификатор